### ISSUE TITLE
Break up index.html into logical units (i.e., header/footer/menu/etc... along with sections)

### ISSUE THREAD

**Issue by kevinjalbert** [SMastroianni/smastroianni.github.io#2]
There is no need for the `index.html` to be a single unit. We can break this up into smaller units which then could be reused in other locations/pages.

**Comment by SMastroianni** [comment]
Ok, thanks. gotta get my head back into the game. Hopefully I'l be able to do a bit of work tonight.
Thanks for all your help!

Date: Mon, 17 Nov 2014 12:10:42 -0800

**Comment by kevinjalbert** [comment]
Closed due to #3.
